import React from "react";
import Layout from "../components/Layout";
import { FileText } from "lucide-react";

const Section = ({ title, children }) => (
  <div className="mb-10">
    <h2 className="text-xl font-bold text-white mb-3 border-l-4 border-orange-500 pl-4">{title}</h2>
    <div className="text-slate-300 text-sm md:text-base leading-relaxed space-y-3 pl-4">{children}</div>
  </div>
);

const Terms = () => (
  <Layout noPadding={false}>
    <div className="min-h-screen bg-slate-900 py-20 px-6 md:px-12">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-12">
          <div className="w-14 h-14 rounded-2xl bg-orange-500/20 text-orange-400 flex items-center justify-center shrink-0">
            <FileText size={28} />
          </div>
          <div>
            <h1 className="text-3xl md:text-4xl font-extrabold text-white">Terms of Service</h1>
            <p className="text-slate-400 text-sm mt-1">Last updated: June 2025</p>
          </div>
        </div>

        <p className="text-slate-300 text-base leading-relaxed mb-10">
          Welcome to Klarify. By accessing or using our platform at <span className="text-orange-400">klarifypath.com</span>, you agree to be bound by these Terms of Service. Please read them carefully.
        </p>

        <Section title="1. About the Service">
          <p>
            Klarify is an academic guidance platform designed to help Cameroonian students explore university programs, search GCE results, and plan their academic and career paths. Our services are provided free of charge and are intended for informational and orientation purposes.
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            You must be at least 13 years of age to use Klarify. By using this platform, you confirm that you meet this requirement. Students under 18 should use the platform with parental awareness.
          </p>
        </Section>

        <Section title="3. User Accounts">
          <p>When you create an account:</p>
          <ul className="list-disc list-inside space-y-2 mt-2">
            <li>You are responsible for keeping your login credentials secure</li>
            <li>You agree to provide accurate information</li>
            <li>You may not create accounts on behalf of others without their consent</li>
            <li>We reserve the right to suspend accounts that violate these terms</li>
          </ul>
        </Section>

        <Section title="4. GCE Results Disclaimer">
          <p>
            The GCE results available on this platform are sourced from official GCE Board publications. Klarify is <strong className="text-white">not affiliated with the Cameroon GCE Board</strong>. We do not alter, certify, or guarantee the accuracy of any results displayed. For official confirmation of results, always refer to the Cameroon GCE Board directly.
          </p>
        </Section>

        <Section title="5. Academic Recommendations">
          <p>
            Recommendations provided by our platform are generated by an AI-powered engine based on the information you provide. They are <strong className="text-white">for informational and orientation purposes only</strong> and should not replace professional academic counseling. Always verify program requirements with the respective institution.
          </p>
        </Section>

        <Section title="6. Prohibited Conduct">
          <p>You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 mt-2">
            <li>Use the platform for any unlawful purpose</li>
            <li>Attempt to access another user's account</li>
            <li>Scrape, copy, or redistribute our data without written permission</li>
            <li>Abuse or disrupt the platform's services</li>
          </ul>
        </Section>

        <Section title="7. Intellectual Property">
          <p>
            All content, branding, code, and design on Klarify is the property of the Klarify team. You may not reproduce or redistribute any part of the platform without explicit written permission.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            Klarify is provided "as is" without warranties of any kind. We are not liable for any decisions made based on information provided by the platform. Academic outcomes are solely the responsibility of the student and their institution.
          </p>
        </Section>

        <Section title="9. Changes to Terms">
          <p>
            We reserve the right to update these Terms at any time. Continued use of the platform after changes are posted constitutes acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="10. Contact">
          <p>For any questions about these Terms, please contact us at:</p>
          <p className="mt-2"><a href="mailto:hello@klarifypath.com" className="text-orange-400 hover:text-orange-300 transition-colors font-bold">hello@klarifypath.com</a></p>
        </Section>

        <div className="mt-12 p-6 bg-white/5 border border-white/10 rounded-2xl text-center">
          <p className="text-slate-400 text-sm">By using Klarify, you agree to these Terms of Service and our Privacy Policy.</p>
        </div>
      </div>
    </div>
  </Layout>
);

export default Terms;
